---
title: "Non-Option Portfolio Simulations"
author: "Jack Yoon"
output:
  pdf_document:
    toc: true
    number_sections: true
toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

\section{Data and Libraries}

```{r,cache=T}
#Load Libraries 
library(quantmod)
library(ggplot2)

#Use Quantmod to get data

#Stocks
getSymbols("SPY",
           from = "2000/01/07",
           to = "2021/12/31",
           periodicity = "daily")

#Volatility
getSymbols("^VIX",
           from = "2000/01/07",
           to = "2021/12/31",
           periodicity = "daily")

#Gold
getSymbols("SGGDX",
           from = "2000/01/07",
           to = "2021/12/31",
           periodicity = "daily")

#Commodities
getSymbols("^BCOM",
           from = "2000/01/07",
           to = "2021/12/31",
           periodicity = "daily")

#Real Estate
getSymbols("FRESX",
           from = "2000/01/07",
           to = "2021/12/31",
           periodicity = "daily")

#Vanguard Long-Term Investment-Grade
getSymbols("VWESX",
           from = "2000/01/07",
           to = "2021/12/31",
           periodicity = "daily")


#Cash Proxy (3-Month Treasuries)
getSymbols("DGS3MO",src = "FRED",from="2000/01/07",to="2021/12/31")

#10-Year Treasuries
getSymbols("DGS10",src = "FRED",from="2000/01/07",to="2021/12/31")

#Create a merged data table of SPY, VIX data
total = data.frame(merge(VIX,SPY,SGGDX,BCOM,FRESX,VWESX,DGS3MO,DGS10))

#Calculate daily changes in dividend/split-adjusted SPY values
total$return.daily.adjust = rep(NA,nrow(total))
total$gld.return.daily = rep(NA,nrow(total))
total$dbc.return.daily = rep(NA,nrow(total))
total$re.return.daily = rep(NA,nrow(total))
for(i in 2:nrow(total)){
  total$return.daily.adjust[i] = total$SPY.Adjusted[i]/total$SPY.Adjusted[i-1]-1
  total$gld.return.daily[i] = total$SGGDX.Adjusted[i]/total$SGGDX.Adjusted[i-1]-1
  total$dbc.return.daily[i] = total$BCOM.Adjusted[i]/total$BCOM.Adjusted[i-1]-1
  total$re.return.daily[i] = total$FRESX.Adjusted[i]/total$FRESX.Adjusted[i-1]-1
  total$bond.return.daily[i] = total$VWESX.Adjusted[i]/total$VWESX.Adjusted[i-1]-1
}
total = total[8871:dim(total)[1],]
total = na.omit(total)
```

\section{10-Year Return Profiles / S&P500, Diversified Fan of Outcomes}

```{r}
#Baseline Fan of Outcomes (Daily)
fan = rep(NA,dim(total)[1]-240*10)
for(i in 1:(dim(total)[1]-240*10)){
  fan[i] = (total[i+240*10,]$SPY.Adjusted/total[i,]$SPY.Adjusted)^(1/1)-1
}
hist(fan)
quantile(fan,na.rm=T)

#Baseline Fan of Outcomes (Daily)
```

```{r}
#60-40 Portfolio
library(BondValuation)

fan6040 = rep(NA,dim(total)[1])

#Initialize values
spy.portval = 6000
bond.portval = 4000
index.portval = rep(NA,dim(total)[1])
index.portval[1] = 10000
years = seq(1999,2021)
j=1

for(i in 1:dim(total)[1]){
  #Assume AFS; daily rebalancing
  spy.return = total$SPY.Adjusted[j+i]/total$SPY.Adjusted[j+i-1]-1
  spy.portval = spy.portval*(1+spy.return)
  index.portval[i+1] = index.portval[i]*(1+spy.return)
  
  #Bond Interest Return
  bond.portval = bond.portval*(1+total$bond.return.daily[j+i])
  
  #Rebalance monthly
  if(i %% 30 == 1 & i != 1){
    
    #Calculate proportions
    prop = (spy.portval/(bond.portval+spy.portval))
    
    if(prop > 0.6){
      reduction = spy.portval-0.6*(bond.portval+spy.portval)
      spy.portval = spy.portval-reduction
      bond.portval = bond.portval+reduction
      avg.yield = total$DGS10[j+i]
    }
    
    if(prop < 0.6){
      increase = 0.6*(bond.portval+spy.portval)-spy.portval
      spy.portval = spy.portval+increase
      bond.portval = bond.portval-increase
      avg.yield = total$DGS10[j+i]
    }
  }
  
  fan6040[i] = spy.portval+bond.portval
}


#Calculate returns
growth.plot = rep(NA,23)
spy.plot = rep(NA,23)

growth.plot[1] = fan6040[1]
spy.plot[1] = index.portval[1]
growth.rate = rep(NA,23)

for(i in 1:22){
  growth.plot[i+1] = fan6040[240*i]
  spy.plot[i+1] = index.portval[240*i]
  growth.rate[i] = growth.plot[i+1]/growth.plot[i]
}

plot(years,spy.plot,type="l",main="Value of $10,000 Invested in SPY vs. 60-40, 2000-2021",xlab="Years",ylab="Value of Initial $10,000 Investment",ylim=c(0,60000))
lines(years,growth.plot,col="blue")
legend(x=2000,y=40000,legend = c("SPY","60-40"),col=c("black","blue"),lty=1,cex=0.8)

cagr.6040 = rep(NA,22-1+1)
for(i in 1:(22-1+1)){
  cagr.6040[i]=(growth.plot[i+1]/growth.plot[i])^(1/1)-1
}
quantile(cagr.6040,na.rm=T)
```

```{r}
#Diversified Portfolio (25% Cash, 25% S&P, 25% Gold, 25% 10-Year)
fan.diversified = rep(NA,dim(total)[1])

j=1
#Initialize values
cash.portval = 2500
spy.portval = 2500
gold.portval = 2500
bond.portval = 2500
cash.increase = 0
index.portval = rep(NA,dim(total)[1])
index.portval[1] = 10000

for(i in 1:dim(total)[1]){
  fan.diversified[i] = spy.portval+bond.portval+cash.portval+gold.portval
  
  #SPY
  spy.return = total$SPY.Adjusted[j+i]/total$SPY.Adjusted[j+i-1]-1
  spy.portval = spy.portval*(1+spy.return)
  
  #Gold
  gold.return = total$gld.return.daily[j+i]
  gold.portval = gold.portval*(1+gold.return)
  
  #Cash
  cash.daily.return = ((total$DGS3MO[j+i]/100+1)^(1/240)-1)*100
  cash.portval = cash.portval*(1+cash.daily.return/100)
  
  #Bond Interest Return
  bond.portval = bond.portval*(1+total$bond.return.daily[j+i])
  
  index.portval[i+1] = index.portval[i]*(1+spy.return)
  
  if(i %% 30 == 1 & i != 1){
    
    #Calculate proportions
    total.portval = spy.portval + gold.portval + cash.portval + bond.portval
    
    prop.spy = spy.portval/total.portval
    prop.gold = gold.portval/total.portval
    prop.cash = cash.portval/total.portval
    prop.bond = bond.portval/total.portval
    
    #Rule: waterfall out highest-risk assets for the lowest-risk assets (e.g. if proportion of stocks goes beyond 25%, switch into cash first, then bonds, then gold); if proportion of stocks goes under 25%, look for leeway in gold first, then bonds, then cash
    
    #If proportion of stocks is greater than 25%
    if(prop.spy > 0.25){
      reduction = spy.portval-0.25*total.portval
      
      if(prop.cash < 0.25){
        cash.increase = min((0.25-prop.cash)*total.portval,reduction)
        cash.portval = cash.portval + cash.increase
        spy.portval = spy.portval-cash.increase
        
        if(cash.increase < reduction){
          bond.increase = min((0.25-prop.bond)*total.portval,reduction-cash.increase)
          bond.portval = bond.portval + bond.increase
          spy.portval = spy.portval-bond.increase
          
          if(cash.increase + bond.increase < reduction){
            gold.increase = min((0.25-prop.gold)*total.portval,reduction-cash.increase-bond.increase)
            gold.portval = gold.portval + gold.increase
            spy.portval = spy.portval-gold.increase
          }
        }
      }
      
      if(prop.bond < 0.25){
        bond.increase = min((0.25-prop.bond)*total.portval,reduction)
        bond.portval = bond.portval + bond.increase
        spy.portval = spy.portval-bond.increase
        
        if(cash.increase + bond.increase < reduction){
          gold.increase = min((0.25-prop.gold)*total.portval,reduction-bond.increase)
          gold.portval = gold.portval + gold.increase
          spy.portval = spy.portval-gold.increase
        }
      }
      
      if(prop.gold < 0.25){
        gold.increase = min((0.25-prop.gold)*total.portval,reduction)
        gold.portval = gold.portval + gold.increase
        spy.portval = spy.portval-gold.increase
      }
    }
    
    #Proportion of stocks is less than 25%
    if(prop.spy < 0.25){
      increase = 0.25*total.portval - spy.portval
      
      if(prop.gold > 0.25){
        gold.reduction = min((prop.gold-0.25)*total.portval,increase)
        gold.portval = gold.portval - gold.reduction
        spy.portval = spy.portval+gold.reduction
        
        if(gold.reduction < increase){
          bond.reduction = min((prop.bond-0.25)*total.portval,increase-gold.reduction)
          bond.portval = bond.portval - bond.reduction
          spy.portval = spy.portval+bond.reduction
          
          if(gold.reduction + bond.reduction < increase){
            cash.reduction = min((prop.cash-0.25)*total.portval,increase-gold.reduction-bond.reduction)
            cash.portval = cash.portval - cash.reduction
            spy.portval = spy.portval+cash.reduction
          }
        }
      }
      
      if(prop.bond < 0.25){
          bond.reduction = min((prop.bond-0.25)*total.portval,increase)
          bond.portval = bond.portval - bond.reduction
          spy.portval = spy.portval+bond.reduction
          
          if(bond.reduction < increase){
            cash.reduction = min((prop.cash-0.25)*total.portval,increase-bond.reduction)
            cash.portval = cash.portval - cash.reduction
            spy.portval = spy.portval+cash.reduction
          }
      }
      
      if(prop.cash < 0.25){
          cash.reduction = min((prop.cash-0.25)*total.portval,increase)
          cash.portval = cash.portval - cash.reduction
          spy.portval = spy.portval+cash.reduction
      }
    }
        
    avg.yield = total$DGS10[j+i]
   
  }
  
  
  
}

#Calculate returns
growth.plot = rep(NA,23)
spy.plot = rep(NA,23)

growth.plot[1] = fan.diversified[1]
spy.plot[1] = index.portval[1]
growth.rate = rep(NA,23)

for(i in 1:22){
  growth.plot[i+1] = fan.diversified[240*i]
  spy.plot[i+1] = index.portval[240*i]
  growth.rate[i] = growth.plot[i+1]/growth.plot[i]
}


years = seq(1999,2021)
plot(years,spy.plot,type="l",main="Value of $10,000 Invested in SPY vs. Risk Parity 1, 2000-2021",xlab="Years",ylab="Value of Initial $10,000 Investment",ylim=c(0,60000))
lines(years,growth.plot,col="blue")
legend(x=2000,y=40000,legend = c("SPY","Risk Parity 1"),col=c("black","blue"),lty=1,cex=0.8)

cagr.diversified = rep(NA,22-1+1)
cagr.spy = rep(NA,22-1+1)
for(i in 1:(22-1+1)){
  cagr.diversified[i]=(growth.plot[i+1]/growth.plot[i])^(1/1)-1
  cagr.spy[i] = (spy.plot[i+1]/spy.plot[i])^(1/1)-1
}
quantile(cagr.diversified,na.rm=T)
quantile(cagr.spy,na.rm=T)
```

```{r}
#Total Diversified Portfolio (20% Cash, 16% S&P, 16% Gold, 16% Commodities, 16% Real Estate, 16% UST10)
fan.total.diversified = rep(NA,dim(total)[1])

j=1
#Initialize values
cash.portval = 2000
spy.portval = 1600
gold.portval = 1600
com.portval = 1600
re.portval = 1600
bond.portval = 1600
index.portval = rep(NA,dim(total)[1])
index.portval[1] = 10000

for(i in 1:dim(total)[1]){
  fan.total.diversified[i] = spy.portval+bond.portval+cash.portval+gold.portval+re.portval+com.portval
  
  #SPY
  spy.return = total$SPY.Adjusted[j+i]/total$SPY.Adjusted[j+i-1]-1
  spy.portval = spy.portval*(1+spy.return)
  
  #Gold
  gold.return = total$gld.return.daily[j+i]
  gold.portval = gold.portval*(1+gold.return)
  
  #Cash
  cash.daily.return = ((total$DGS3MO[j+i]/100+1)^(1/240)-1)*100
  cash.portval = cash.portval*(1+cash.daily.return/100)
  
  #Commodities
  com.return = total$dbc.return.daily[j+i]
  com.portval = com.portval*(1+com.return)
  
  #Real Estate
  re.return = total$re.return.daily[j+i]
  re.portval = re.portval*(1+re.return)
  
  #Bonds - Assume AFS; daily rebalancing
  #Bond Interest Return
  bond.portval = bond.portval*(1+total$bond.return.daily[j+i])
  
  #Index
  index.portval[i+1] = index.portval[i]*(1+spy.return)
  
  if(i %% 30 == 1 & i != 1){
    #Calculate proportions
    total.portval = spy.portval + gold.portval + cash.portval + bond.portval + re.portval + com.portval
    
    prop.spy = spy.portval/total.portval
    prop.gold = gold.portval/total.portval
    prop.cash = cash.portval/total.portval
    prop.bond = bond.portval/total.portval
    prop.re = re.portval/total.portval
    prop.com = com.portval/total.portval
    
    #Rule: waterfall out highest-risk assets for the lowest-risk assets (e.g. if proportion of stocks goes beyond 25%, switch into cash first, then bonds, then gold); if proportion of stocks goes under 25%, look for leeway in gold first, then bonds, then cash. 
    #Order (high-to-low risk): RE > Com > SPY > GLD > Bond > Cash
    
    #If proportion of stocks is greater than 25%
    if(prop.re > 0.16){
      reduction = re.portval-0.16*total.portval
      
      if(prop.cash < 0.2){
        cash.increase = min((0.2-prop.cash)*total.portval,reduction)
        cash.portval = cash.portval + cash.increase
        re.portval = re.portval-cash.increase
        
        if(cash.increase < reduction){
          bond.increase = min((0.16-prop.bond)*total.portval,reduction-cash.increase)
          bond.portval = bond.portval + bond.increase
          re.portval = re.portval-bond.increase
          
          if(cash.increase + bond.increase < reduction){
            gold.increase = min((0.16-prop.gold)*total.portval,reduction-cash.increase-bond.increase)
            gold.portval = gold.portval + gold.increase
            re.portval = re.portval-gold.increase
            
            if(cash.increase + bond.increase + gold.increase < reduction){
            spy.increase = min((0.16-prop.spy)*total.portval,reduction-cash.increase-bond.increase-gold.increase)
            spy.portval = spy.portval + spy.increase
            re.portval = re.portval-spy.increase
            
              if(cash.increase + bond.increase + gold.increase + spy.increase < reduction){
                com.increase = min((0.16-prop.com)*total.portval,reduction-cash.increase-bond.increase-gold.increase-spy.increase)
                com.portval = com.portval + com.increase
                re.portval = re.portval-com.increase
                }
              }
            }
          }
        }
    
      if(prop.bond < 0.16){
        bond.increase = min((0.16-prop.bond)*total.portval,reduction)
        bond.portval = bond.portval + bond.increase
        re.portval = re.portval-bond.increase
        
        if(bond.increase < reduction){
          gold.increase = min((0.16-prop.gold)*total.portval,reduction-bond.increase)
          gold.portval = gold.portval + gold.increase
          re.portval = re.portval-gold.increase
          
          if(bond.increase + gold.increase < reduction){
          spy.increase = min((0.16-prop.spy)*total.portval,reduction-bond.increase-gold.increase)
          spy.portval = spy.portval + spy.increase
          re.portval = re.portval-spy.increase
          
            if(bond.increase + gold.increase + spy.increase < reduction){
              com.increase = min((0.16-prop.com)*total.portval,reduction-bond.increase-gold.increase-spy.increase)
              com.portval = com.portval + com.increase
              re.portval = re.portval-com.increase
            }
          }
        }
      }
      
      if(prop.gold < 0.16){
        gold.increase = min((0.16-prop.gold)*total.portval,reduction)
        gold.portval = gold.portval + gold.increase
        re.portval = re.portval-gold.increase
        
        if(gold.increase < reduction){
        spy.increase = min((0.16-prop.spy)*total.portval,reduction-gold.increase)
        spy.portval = spy.portval + spy.increase
        re.portval = re.portval-spy.increase
        
          if(gold.increase + spy.increase < reduction){
            com.increase = min((0.16-prop.com)*total.portval,reduction-gold.increase-spy.increase)
            com.portval = com.portval + com.increase
            re.portval = re.portval-com.increase
          }
        }
      }
      
      if(prop.spy < 0.16){
        spy.increase = min((0.16-prop.spy)*total.portval,reduction)
        spy.portval = spy.portval + spy.increase
        re.portval = re.portval-spy.increase
        
        if(spy.increase < reduction){
          com.increase = min((0.16-prop.com)*total.portval,reduction-spy.increase)
          com.portval = com.portval + com.increase
          re.portval = re.portval-com.increase
        }
      }
      
      if(prop.com < 0.16){
          com.increase = min((0.16-prop.com)*total.portval,reduction)
          com.portval = com.portval + com.increase
          re.portval = re.portval-com.increase
      }
      
    }
    
    #Proportion of stocks is less than 25%
    if(prop.re < 0.16){
      increase = 0.16*total.portval - re.portval
      
      if(prop.com > 0.16){
        com.reduction = min((prop.com-0.16)*total.portval,increase)
        com.portval = com.portval - com.reduction
        re.portval = re.portval+com.reduction
        
        if(com.reduction < increase){
          spy.reduction = min((prop.spy-0.16)*total.portval,increase-com.reduction)
          spy.portval = spy.portval - spy.reduction
          re.portval = re.portval+spy.reduction
          
          if(com.reduction + spy.reduction < increase){
            gold.reduction = min((prop.gold-0.16)*total.portval,increase-com.reduction-spy.reduction)
            gold.portval = gold.portval - gold.reduction
            re.portval = re.portval+gold.reduction
            
            if(com.reduction + spy.reduction + gold.reduction < increase){
              bond.reduction = min((prop.bond-0.16)*total.portval,increase-com.reduction-spy.reduction-gold.reduction)
              bond.portval = bond.portval - bond.reduction
              re.portval = re.portval+bond.reduction
              
              if(com.reduction + spy.reduction + gold.reduction + bond.reduction < increase){
                cash.reduction = min((prop.cash-0.2)*total.portval,increase-com.reduction-spy.reduction-gold.reduction-bond.reduction)
                cash.portval = cash.portval - cash.reduction
                re.portval = re.portval+cash.reduction
              }
            }
          }
        }
      }

      ######
      if(prop.spy < 0.16){
        spy.reduction = min((prop.spy-0.16)*total.portval,increase)
        spy.portval = spy.portval - spy.reduction
        re.portval = re.portval+spy.reduction
        
        if(spy.reduction < increase){
          gold.reduction = min((prop.gold-0.16)*total.portval,increase-spy.reduction)
          gold.portval = gold.portval - gold.reduction
          re.portval = re.portval+gold.reduction
          
          if(spy.reduction + gold.reduction < increase){
            bond.reduction = min((prop.bond-0.16)*total.portval,increase-spy.reduction-gold.reduction)
            bond.portval = bond.portval - bond.reduction
            re.portval = re.portval+bond.reduction
            
            if(spy.reduction + gold.reduction + bond.reduction < increase){
              cash.reduction = min((prop.cash-0.2)*total.portval,increase-spy.reduction-gold.reduction-bond.reduction)
              cash.portval = cash.portval - cash.reduction
              re.portval = re.portval+cash.reduction
            }
          }
        }
      }
      
      if(prop.gold < 0.16){
        gold.reduction = min((prop.gold-0.16)*total.portval,increase)
        gold.portval = gold.portval - gold.reduction
        re.portval = re.portval+gold.reduction
        
        if(gold.reduction < increase){
          bond.reduction = min((prop.bond-0.16)*total.portval,increase-gold.reduction)
          bond.portval = bond.portval - bond.reduction
          re.portval = re.portval+bond.reduction
          
          if(gold.reduction + bond.reduction < increase){
            cash.reduction = min((prop.cash-0.2)*total.portval,increase-gold.reduction-bond.reduction)
            cash.portval = cash.portval - cash.reduction
            re.portval = re.portval+cash.reduction
          }
        }
      }
      
      if(prop.bond < 0.16){
        bond.reduction = min((prop.bond-0.16)*total.portval,increase)
        bond.portval = bond.portval - bond.reduction
        re.portval = re.portval+bond.reduction
        
        if(bond.reduction < increase){
          cash.reduction = min((prop.cash-0.2)*total.portval,increase-bond.reduction)
          cash.portval = cash.portval - cash.reduction
          re.portval = re.portval+cash.reduction
        }
      }
      
      if(prop.cash < 0.2){
        cash.reduction = min((prop.cash-0.2)*total.portval,increase)
        cash.portval = cash.portval - cash.reduction
        re.portval = re.portval+cash.reduction
      }
    }
        
    avg.yield = total$DGS10[j+i]
  }
}

#Calculate returns
growth.plot = rep(NA,23)
spy.plot = rep(NA,23)

growth.plot[1] = fan.total.diversified[1]
spy.plot[1] = index.portval[1]
growth.rate = rep(NA,23)

for(i in 1:22){
  growth.plot[i+1] = fan.total.diversified[240*i]
  spy.plot[i+1] = index.portval[240*i]
  growth.rate[i] = growth.plot[i+1]/growth.plot[i]
}


years = seq(1999,2021)
plot(years,spy.plot,type="l",main="Value of $10,000 Invested in SPY vs. Risk Parity 2, 2000-2021",xlab="Years",ylab="Value of Initial $10,000 Investment",ylim=c(0,60000))
lines(years,growth.plot,col="blue")
legend(x=2000,y=40000,legend = c("SPY","Risk Parity 2"),col=c("black","blue"),lty=1,cex=0.8)

cagr.total.diversified = rep(NA,22-1+1)
for(i in 1:(22-1+1)){
  cagr.total.diversified[i]=(growth.plot[i+1]/growth.plot[i])^(1/1)-1
}
quantile(cagr.total.diversified,na.rm=T)
```

```{r}
#Volatility-Managed (Moreira-Muir / Verdad Research)
#In continuous-time finance, expected log welath is maximized by investing a fraction (mu / sigma^2), where mu is expected future excess return; sigma^2 is expected future variance
#Use VIX as an estimator for expected future variance
#https://www.indexologyblog.com/2013/10/18/turn-vix-into-information-you-can-use/

#Calculate 30-day implied volatility (1 std dev)
total$vol.implied = (total$VIX.Close/100)/sqrt(12)

#Calculate 30-day implied variance

total$var.implied = total$vol.implied^2

#Modulate equity holdings by (c/sigma^2), rest put into 3-month T-bills (as proxy for risk-free cash). Scale c by maximum VIX.


fan.vol = rep(data=NA,dim(total)[1])

vals = seq(0.01,1,0.2)

returns = rep(NA,length(vals))

c = 0.11*max(total$var.implied)

j=1
spy.portval = 10000
cash.portval = 0
index.portval = rep(NA,dim(total)[1])
index.portval[1] = 10000

for(i in 1:dim(total)[1]){
  #Record
  fan.vol[i] = spy.portval+cash.portval
  
  #SPY
  spy.return = total$SPY.Adjusted[j+i]/total$SPY.Adjusted[j+i-1]-1
  spy.portval = spy.portval*(1+spy.return)
  
  #Index
  index.portval[i+1] = index.portval[i]*(1+spy.return)
  
  #Cash
  cash.daily.return = ((total$DGS3MO[j+i]/100+1)^(1/240)-1)*100
  cash.portval = cash.portval*(1+cash.daily.return/100)
  
  #Fractional allocation to equities
  total.portval = spy.portval+cash.portval
  prop.spy = spy.portval/total.portval
  prop.cash = cash.portval/total.portval
  fraction = min(c/total$var.implied[j+i],1)

  #Rebalance
  spy.portval = fraction*total.portval
  cash.portval = (1-fraction)*total.portval
}

#Calculate returns
growth.plot = rep(NA,23)
spy.plot = rep(NA,23)

growth.plot[1] = fan.vol[1]
spy.plot[1] = index.portval[1]
growth.rate = rep(NA,23)

for(i in 1:22){
  growth.plot[i+1] = fan.vol[240*i]
  spy.plot[i+1] = index.portval[240*i]
  growth.rate[i] = growth.plot[i+1]/growth.plot[i]
}

years = seq(1999,2021)
plot(years,spy.plot,type="l",main="Value of $10,000 Invested in SPY vs. Vol. Managed, 2000-2021",xlab="Years",ylab="Value of Initial $10,000 Investment",ylim=c(0,60000))
lines(years,growth.plot,col="blue")
legend(x=2000,y=40000,legend = c("SPY","VM"),col=c("black","blue"),lty=1,cex=0.8)

cagr.vol = rep(NA,22-1+1)
for(i in 1:(22-1+1)){
  cagr.vol[i]=(growth.plot[i+1]/growth.plot[i])^(1/1)-1
}
quantile(cagr.vol,na.rm=T)
```

Stop loss strategy.

```{r}
#Stop Loss
fan.stop = rep(NA,ncol=dim(total)[1])
limit = 0.1

j=1
spy.portval = 10000
cash.portval = 0
protection = 0
index.portval = rep(NA,dim(total)[1])
index.portval[23] = 10000

for(i in 23:dim(total)[1]-1){
  fan.stop[i] = spy.portval+cash.portval  
  
  #SPY
  spy.return = total$SPY.Adjusted[j+i]/total$SPY.Adjusted[j+i-1]-1
  spy.portval = spy.portval*(1+spy.return)
  
  #Index
  index.portval[i+1] = index.portval[i]*(1+spy.return)
  
  #Cash
  cash.daily.return = ((total$DGS3MO[j+i]/100+1)^(1/240)-1)*100
  cash.portval = cash.portval*(1+cash.daily.return/100)
  
  if((total$SPY.Adjusted[j+i] < (1-limit)*total$SPY.Adjusted[j+i-22]) & protection == 0){
    #Activate stop-loss; shift into all cash for 22 trading days
    cash.portval = spy.portval
    spy.portval = 0
    protection = 1
    count = 5
  }
  
  if(protection == 1){
    count = count-1
    if(count == 0){
      protection = 0
      spy.portval = cash.portval
      cash.portval = 0
    }
  }
}

#Calculate returns
growth.plot = rep(NA,23)
spy.plot = rep(NA,23)

growth.plot[1] = fan.stop[23]
spy.plot[1] = index.portval[23]
growth.rate = rep(NA,23)

for(i in 1:22){
  growth.plot[i+1] = fan.stop[240*i]
  spy.plot[i+1] = index.portval[240*i]
  growth.rate[i] = growth.plot[i+1]/growth.plot[i]
}

years = seq(1999,2021)
plot(years,spy.plot,type="l",main="Value of $10,000 Invested in SPY vs. Stop Loss, 2000-2021",xlab="Years",ylab="Value of Initial $10,000 Investment",ylim=c(0,60000))
lines(years,growth.plot,col="blue")
legend(x=2000,y=40000,legend = c("SPY","SL"),col=c("black","blue"),lty=1,cex=0.8)

cagr.stop = rep(NA,22-1+1)
for(i in 1:(22-1+1)){
  cagr.stop[i]=(growth.plot[i+1]/growth.plot[i])^(1/1)-1
}
quantile(cagr.stop,na.rm=T)
```

```{r}
par(mfrow=c(4,2))
par(cex=0.7, mai=c(0.3,0.3,0.3,0.3))
plot(density(fan),main="Market Benchmark",xlab="10-Year Rolling Returns",ylab="Density",ylim=c(0,30))

plot(density(fan),main="60-40",xlab="10-Year Rolling Returns",ylab="Density",ylim=c(0,30))
lines(density(fan6040.returns),col="blue")

plot(density(fan),main="Risk Parity 1",xlab="10-Year Rolling Returns",ylab="Density",ylim=c(0,30))
lines(density(fan.diversified.returns),col="blue")

plot(density(fan),main="Risk Parity 2",xlab="10-Year Rolling Returns",ylab="Density",ylim=c(0,30))
lines(density(fan.total.diversified.returns),col="blue")

plot(density(fan),main="Vol. Managed",xlab="10-Year Rolling Returns",ylab="Density",ylim=c(0,30))
lines(density(fan.vol.returns),col="blue")

plot(density(fan),main="Tail Risk 1",xlab="10-Year Rolling Returns",ylab="Density",ylim=c(0,30))
lines(density(tenyear.return1,na.rm=T),col="blue")

plot(density(fan),main="Tail Risk 2",xlab="10-Year Rolling Returns",ylab="Density",ylim=c(0,30))
lines(density(tenyear.return,na.rm=T),col="blue")

plot(density(fan),main="Stop Loss",xlab="10-Year Rolling Returns",ylab="Density",ylim=c(0,30))
lines(density(fan.stop.returns,na.rm=T),col="blue")
```

```{r}
bar.names = c("Benchmark","60/40","RP1","RP2","VM","TR1","TR2","SL")
barplot(c(quantile(cagr.spy,na.rm=T)[1],quantile(cagr.6040,na.rm=T)[1],quantile(cagr.diversified,na.rm=T)[1],quantile(cagr.total.diversified,na.rm=T)[1],quantile(cagr.vol,na.rm=T)[1],quantile(yearlyreturns1,na.rm=T)[1],quantile(yearlyreturns,na.rm=T)[1],quantile(cagr.stop,na.rm=T)[1]),names.arg=bar.names,main="Maximum Yearly Drawdowns, 2000-2021",col=c("blue","grey","tomato","orange","purple","green","turquoise","violet"))

bar.names = c("Benchmark","60/40","RP1","RP2","VM","TR1","TR2","SL")
barplot(c(quantile(cagr.spy,na.rm=T)[5],quantile(cagr.6040,na.rm=T)[5],quantile(cagr.diversified,na.rm=T)[5],quantile(cagr.total.diversified,na.rm=T)[5],quantile(cagr.vol,na.rm=T)[5],quantile(yearlyreturns1,na.rm=T)[5],quantile(yearlyreturns,na.rm=T)[5],quantile(cagr.stop,na.rm=T)[5]),names.arg=bar.names,main="Maximum Yearly Increases, 2000-2021",col=c("blue","grey","tomato","orange","purple","green","turquoise","violet"))
```

```{r}
bar.names = c("Benchmark","60/40","RP1","RP2","VM","TR1","TR2","SL")
barplot(c(cagr.spy[3],cagr.6040[3],cagr.diversified[3],cagr.total.diversified[3],cagr.vol[3],yearlyreturns1[4],yearlyreturns[4],cagr.stop[3]),names.arg=bar.names,main="YoY Gain / Loss in 2002",col=c("blue","grey","tomato","orange","purple","green","turquoise","violet"))

bar.names = c("Benchmark","60/40","RP1","RP2","VM","TR1","TR2","SL")
barplot(c(cagr.spy[9],cagr.6040[9],cagr.diversified[9],cagr.total.diversified[9],cagr.vol[9],yearlyreturns1[10],yearlyreturns[10],cagr.stop[9]),names.arg=bar.names,main="YoY Gain / Loss in 2008",col=c("blue","grey","tomato","orange","purple","green","turquoise","violet"))

bar.names = c("Benchmark","60/40","RP1","RP2","VM","TR1","TR2","SL")
barplot(c(cagr.spy[21],cagr.6040[21],cagr.diversified[21],cagr.total.diversified[21],cagr.vol[21],yearlyreturns1[22],yearlyreturns[22],cagr.stop[21]),names.arg=bar.names,main="YoY Gain / Loss in 2020",col=c("blue","grey","tomato","orange","purple","green","turquoise","violet"))


drawdowns.2002 = c(cagr.spy[3],cagr.6040[3],cagr.diversified[3],cagr.total.diversified[3],cagr.vol[3],yearlyreturns1[4],yearlyreturns[4],cagr.stop[3])-cagr.spy[3]

drawdowns.2008 = c(cagr.spy[9],cagr.6040[9],cagr.diversified[9],cagr.total.diversified[9],cagr.vol[9],yearlyreturns1[10],yearlyreturns[10],cagr.stop[9])-cagr.spy[9]

drawdowns.2020 = c(cagr.spy[21],cagr.6040[21],cagr.diversified[21],cagr.total.diversified[21],cagr.vol[21],yearlyreturns1[22],yearlyreturns[22],cagr.stop[21])-cagr.spy[21]

drawdowns = data.frame(drawdowns.2002,drawdowns.2008,drawdowns.2020)
drawdowns$average = rowMeans(drawdowns)
barplot(drawdowns$average[2:8],names.arg=bar.names[2:length(bar.names)],main="Average Arithmetic Excess Return in 2000, 2002, 2008",col=c("grey","tomato","orange","purple","green","turquoise","violet"))
```

